#!/usr/bin/with-contenv bash
if [ "$enableQueueCleaner" != "true" ]; then
	echo "QueueCleaner.bash Script disabled, enable by setting parameter: enableQueueCleaner=true"
	sleep infinity
else
  su abc -s "/config/extended/scripts/QueueCleaner.bash"
fi
exit
